build-job:
  stage: .pre
  script:
    - echo "GOOD"
    - echo "'$SSH_KEY'"
pro:
  stage: deploy
  script:
    - cd /home/groofi/project
    - git status
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git pull origin master
    - source venv/bin/activate
    - python manage.py makemigrations
    - python manage.py migrate
    - pip install -r requirements