version: '3.9'

stages:
  - test
  - deploy
  
test:
  stage: test
  tags:
    - test_development
  image: python:3.10
  services:
    - postgres:latest
  variables:
    SECRET_KEY: $SECRET_KEY
    POSTGRES_DB: 'test_db'
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: 'test_pass'
    HOST: 'postgres'
    PORT: '5432'
    DEBUG: 'True'
  script:
    - apt-get update && apt-get install -y pipenv
    - pipenv install --system
    - python manage.py test
  only:
    - merge_requests
    
deploy:
  tags:
    - deploy_development
  stage: deploy
  only:
    refs:
      - development
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
      command: ["--insecure-registry=registry.gitlab.com"]
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock    
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - apk add --no-cache docker-compose
  script:
    - echo "$ENV_FILE" > .env
    - docker-compose up -d

