version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: hermes_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - hermes_net
    restart: unless-stopped
    command: postgres -c listen_addresses='*'
    
  nginx:
    image: nginx
    container_name: hermes_nginx
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/app/static
    networks:
      - hermes_net
    restart: unless-stopped
    depends_on:
      - hermes 

  hermes:
    build:
      context: .
      dockerfile: hermes.Dockerfile
    container_name: hermes_django
    env_file:
      - .env     
    networks:
      - hermes_net
    volumes:
      - staticfiles:/app/static    
    restart: unless-stopped
    depends_on:
      - postgres 
    
networks:
  hermes_net:
    driver: bridge
    
volumes:
  pgdata:
    driver: local
  staticfiles:
    driver: local



