# Generated by Django 4.1.1 on 2022-09-11 13:52

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128, verbose_name='Автор')),
                ('name', models.CharField(max_length=128, verbose_name='Название книги')),
                ('made_in', models.CharField(max_length=64, verbose_name='Издательство')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('management', models.PositiveIntegerField(verbose_name='Номер коробки, где лежит книга')),
            ],
            options={
                'verbose_name': 'Книгу',
                'verbose_name_plural': 'Книги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=books.models.directory_path, verbose_name='Картинка книги')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Фотографию книги',
                'verbose_name_plural': 'Фотографии книг',
                'ordering': ['book'],
            },
        ),
    ]
