# Generated by Django 4.1.1 on 2022-10-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='management',
            field=models.CharField(max_length=128, verbose_name='Индификатор коробки, где лежит книга'),
        ),
    ]
