# Generated by Django 4.1.1 on 2023-03-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название коробки')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='Описание содержимого коробки')),
            ],
            options={
                'verbose_name': 'Коробку',
                'verbose_name_plural': 'Коробки',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='books',
            name='management',
        ),
        migrations.AddField(
            model_name='books',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.boxes', verbose_name='Коробка, где лежит книга'),
        ),
    ]
